import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Serif } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";
import SidebarShell from './components/SidebarShell';
import { Providers } from './components/Providers';
import { cn } from "@/lib/utils";

const notoSerif = Noto_Serif({subsets:['latin'],variable:'--font-serif'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const role = await getRoleFromCookie();

  return (
    <html lang="en" className={cn("dark font-serif", notoSerif.variable)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen overflow-hidden bg-black`}
        style={{
          backgroundImage: "url('/Dolmites.jpg')",
          backgroundSize: 'cover',
          backgroundPosition: 'center',
          backgroundAttachment: 'fixed',
        }}
      >
        <div className="absolute inset-0 bg-black/40 pointer-events-none" />
        <SidebarShell role={role}>
          <Providers>{children}</Providers>
        </SidebarShell>
      </body>
    </html>
  );
}

async function getRoleFromCookie(): Promise<string | null> {
  try {
    const cookieStore = await cookies();
    const token = cookieStore.get('firebaseToken')?.value;
    if (!token) return null;
    const payload = token.split('.')[1];
    const decoded = JSON.parse(Buffer.from(payload, 'base64url').toString());
    return (decoded?.role as string) ?? null;
  } catch {
    return null;
  }
}
